npocccties/chiloportal

- backend/.env.dev-server-debug
- backend/docker-compose.yml
resolve #93
以下への対応です
> > webroot を環境変数、そこから先を固定にするとかで良いのではないでしょうか。
> 
> https://github.com/npocccties/chiloportal/tree/develop/backend#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%81%AE%E8%AA%AC%E6%98%8E にあるとおりバックエンドとしては環境変数 `IMAGE_DIR` が存在しているので、
> 
> - [ ] フロントエンド側でインポート用のディレクトリを用意する
> - [ ] [env.dev-server-debug](https://github.com/npocccties/chiloportal/blob/develop/backend/.env.dev-server-debug)のIMAGE_DIRを用意したディレクトリへの相対パスに変更する
> 
> という作業が必要かなと思いました（ちがっていれば指摘いただければと）
_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/93#issuecomment-1259062146_
> chore: フロントエンド側の画像インポート先の用意

- frontend/.vim/coc-settings.json
意図しないファイルタイプを指定しており `.tsx` `.jsx` 編集時整形が効かない件への対応
> chore: エディタの保存時整形対象のファイルタイプの調整

- frontend/lib/use-consumers.ts
- frontend/lib/use-portal-categories.ts
- frontend/package.json
- frontend/yarn.lock
resolve #3
共通レイアウト（ヘッダー / フッター）で必要なデータを
クライアント側で取得する目的
> feat: useConsumers / usePortalCategories フックの実装

- frontend/package.json
yarn dev:path のプロセスが終了せず
開発サーバー起動のコマンドが実行されないため
並列にコマンドを実行することで対処
> fix: yarn dev 時開発サーバーが起動しない

- frontend/pages/search.tsx
下記のフロントエンドサーバーエラーへの対応
undefined のシリアライズに失敗していることが原因
文字列を想定するクエリパラメータなので常に文字列が渡されるように対処
```
Error: Error serializing `.keyword` returned from `getServerSideProps` in "/search".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```
> fix: Error serializing `.keyword`

- frontend/pages/portal_categories/[portalCategoryId].tsx
モックサーバーがランダム値を返すためURLパラメータにヒットする
ポータルカテゴリが必ずしも含まれないことが原因
モックサーバー利用時単一のポータルカテゴリを別途生成することで対処
> fix: モックサーバー使用時ポータルカテゴリの抽出に失敗する

- frontend/tailwind.config.js
contents として指定する glob で考慮できていないことが原因
https://tailwindcss.com/docs/content-configuration
> fix: templates 配下のコンポーネントで tailwindcss が使用できない

- frontend/lib/use-consumers.ts
- frontend/lib/use-portal-categories.ts
- frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
- frontend/pages/consumers/[consumerId]/index.tsx
- frontend/pages/index.tsx
- frontend/pages/portal_categories/[portalCategoryId].tsx
- frontend/pages/search.tsx
- frontend/pages/wisdom_badges/[wisdomBadgesId].tsx
`$get()` を使用すればパースされたレスポンスボディが得られるので
それを利用することで抽出のためのコードを削減する目的
> refactor: 冗長なレスポンスの抽出

- frontend/tailwind.config.js
以下への対応
> @knokmki612 デザインシステムのカラー定義について共有
> 
> https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OKUTEP?node-id=731%3A6445
> 
> グレースケールについて、今回は少し赤みをもたせた tailwind css の colors.stone を使うつもりです。
> 
_Originally posted by @Hidetaro7 in https://github.com/npocccties/chiloportal/issues/194#issuecomment-1280421670_
> feat: 色の設定

- frontend/package.json
- frontend/yarn.lock
#181 の影響で暗黙的に（子孫関係で）依存しているパッケージを
明示的に指定する必要がなくなったため
> chore(deps): 不要な依存関係を取り除く

- frontend/lib/use-badges-frameworks.ts
> fix: バッジと関連性のないコンシューマーが含まれうる

- frontend/components/Header.tsx
リンク要素がブロック要素でないかつ
リスト要素がクリッカブル想定であった古いスタイルが残っていることが原因
> fix: 押せそうなポインターと背景色なのに画面遷移しないことがある

- frontend/.eslintrc.yaml
期待するディレクトリに対して期待する命名規則が適用されないケースがあるため
> chore: filename-match-exported の調整

- frontend/components/Header.tsx
> fix: 育成指標あるいはカテゴリの件数が多いと Popover が画面からはみ出る

- frontend/lib/use-portal-categories.ts
- frontend/lib/use-wisdom-badges-consumers.ts
- frontend/pages/search.tsx
- swr のキーの命名規則の統一
- 参照する型が結果的に同じだが実体が不一致
> refactor: コードの整理

- backend/deploy.sh
以下への対応
> err: docker: Error response from daemon: Conflict. The container name "/frontend" is already in use by container "8ecccd086591eb2451b837ba33b400360208b30681369c3bb7c74184eb218f10". You have to remove (or rename) that container to be able to reuse that name.
https://github.com/npocccties/chiloportal/actions/runs/3341623209/jobs/5533016280#step:3:4479
> fix: デプロイ時 Docker コンテナー名が衝突している

- frontend/components/WisdomBadgesCard.tsx
- frontend/components/WisdomBadgesItem.tsx
- frontend/lib/issuer.ts
URL コンストラクターが例外を投げていることが原因
例外処理を追加することで対処
> fix: issuer の URL のフォーマットが無効のとき描画に失敗する

- .github/workflows/frontend.yaml
resolve #391
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: set-output の \$GITHUB_OUTPUT への移行

- frontend/.prettierignore
いずれもmsw、pathpidaによって生成されるファイルであるため
> chore: 整形対象外のファイルの追加

- .github/workflows/frontend-docker.yaml
- frontend/.dockerignore
- frontend/Dockerfile
- frontend/README.md
- frontend/package.json
- Vercel へのデプロイ手順廃止
- Docker 環境でのデプロイ手順作成
- モック関連のパッケージも Docker で動作するよう依存関係更新
> chore: --build-args 廃止 & docker build 時 .env を参照するように

- frontend/.gitignore
> chore: .env{,.production} を Git 管理対象外にする

- frontend/components/Chat.tsx
fixed #460
該当件数が3件以下の場合を考慮していないことが原因
> fix: チャット検索結果で他は0件の時でも他が表示される

- frontend/components/WisdomBadgesCard.tsx
- frontend/components/WisdomBadgesItem.tsx
- 発行が折り返される
- 画像が親要素の縦幅でアスペクト比が維持されない
ことへの対応です
> fix: 発行者の見た目が折り返し時意図しない見た目になる

- frontend/.env.test
- frontend/.gitignore
- frontend/README.md
テスト用環境変数を参照利用する必要が引き続きあるが
リポジトリにテスト用の値を含めないという方針になったため
> chore: .env.test をリポジトリから取り除くように

- frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
- frontend/templates/Stage.tsx
どの箇所で flatMap すべきか、あるいは Promise.all で配列を得るべきかの
検討不足によるもの
この修正によって指標項目の内容に応じてクライアント側での
例外が発生する場合がある現象の改善が期待されます
> fix: 指標項目別能力バッジの集計処理が意図しない配列のネストになっている

- frontend/components/SearchForm.tsx
- frontend/pages/search.tsx
resolve #510
以下の変更によって対処
- UI として検索可能にしない
- 直接 URL にアクセスした場合ポータルトップにリダイレクトする
> feat: 空文字列での検索は許容しない

- frontend/components/Menu.tsx
> fix: モバイルメニューのエントリー数によっては覆い被さらない

- frontend/components/Layout.tsx
特定のビューポートサイズかつタッチスクリーンでの操作で
チャットを閉じるボタンへアクセス不能になる場合があるため
上に重なることが操作上望ましいように思った
> fix: チャットがグローバルメニューヘッダーより下に重なる

- Dockerfile.frontend
- backend/chiloportal/responses.py
- backend/chiloportal/tests/views/localhost/base_api_view_tests.py
- backend/chiloportal/tests/views/localhost/test_issuer_list.py
- backend/chiloportal/urls.py
- backend/chiloportal/views/__init__.py
- backend/chiloportal/views/issuer_list.py
- backend/doc/openapi.yaml
- frontend/mocks/faker.ts
- frontend/mocks/handlers.ts
ref #680 #681 #683
以下の方法で追加分のテストをパスすることを確認。
```
cd backend
cp .env.localhost .env
cp docker-compose.localhost.yml docker-compose.yml
docker compose up
docker compose exec app pytest
```
また、Django管理画面よりデータを追加して期待するレスポンスが得られることを確認。
> feat: 発行機関を一覧するAPIの実装

- frontend/components/Chat.tsx
- frontend/mocks/faker.ts
- frontend/mocks/handlers.ts
- frontend/pages/portal_categories/[portalCategoryId].tsx
- frontend/pages/search.tsx
resolve #776
API の振る舞いとして page_number クエリパラメーター未指定時
ページネーションせず全件のバッジが返却される実装になっており
フロントエンドの実装として考慮していない点に対応します
> fix: p クエリパラメーター未指定時全件のバッジが画面に表示される

- frontend/pages/discover.tsx
resolve #807
誤ってフロントエンドで受け取るクエリパラメーターを使用していることが原因
> fix: 無効な stage_id が /framework/stage/list に渡されうる

- .dockerignore
.dockerignore に追記してビルドコンテキストから除外することで対処
> fix: 読み取り権限のないファイルをビルドコンテキストに含めようとして失敗する 

- frontend/components/WisdomBadgesItem.tsx
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OZONE-edu?type=design&node-id=3006-9143&mode=design&t=R1L7LpisJuW4JjCY-4 の指定にあわせて見た目を更新します:
> https://dev-portal.oku.cccties.org/discover
> 
> を見ると、hover時に背景色が変わっているが、面積が多く空白が多い場合はなるべくこの方法を避けたい。
> 
> 少し控えめな変化でhover対応したいので、text-gray-700 hover:text-black で進めたい。
> feat(WisdomBadgesItem): ホバーの見た目は文字色のみで表現する

- frontend/templates/Issuer.tsx
resolve #740
モバイル表示時大学が発行した能力バッジ一覧を表示する機能には非対応です
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OZONE-edu?type=design&node-id=2219-12004&mode=design&t=Mu9tkoPb95If5UAp-4
> feat: 大学トップの見た目の整理、モバイルレイアウト

- frontend/templates/Issuer.tsx
以下に対応します
> モバイル時、大学のロゴが入らないと判断むずかしいですが、ロゴと見出しの間が近づきすぎになっているように見えます。
https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U?node-id=2219:12004&mode=design#721413182
> feat: ページヘッダーとコンテンツの余白の調整

- frontend/templates/WisdomBadges.tsx
> fix: 意図しないサイズで大学ロゴが表示される

- frontend/pages/search.tsx
- frontend/templates/Search.tsx
検索キーワードが空文字列の場合はAPIリクエストしないことで対処
> fix: 無効な値をキーワード検索APIに渡しうる

- frontend/templates/Discover.tsx
> fix: 学びを探すの教員育成指標のステージが切り替わらない

- frontend/lib/env.ts
Number(underined) ?? 30 の前者は nullish ではないことに起因
> NEXT_PUBLIC_API_PER_PAGE 未指定時期待しない値（NaN）が使用される点については別途対応します。
_Originally posted by @knokmki612 in https://github.com/npocccties/chiloportal/issues/847#issuecomment-1990437662_
> fix: NEXT_PUBLIC_API_PER_PAGE 未指定時初期値が使用されない

- frontend/components/Header.tsx
- frontend/components/SearchForm.tsx
これによりキーワード検索画面への動線がいずれのビューポートでも提供されます
> feat: md ビューポート幅でも検索欄は表示する

- frontend/components/Header.tsx
- frontend/components/Menu.tsx
グローバルメニューの「大学トップ」→「発行元トップ」に用語を揃えた方が良さそう。
発行元が大学とは限らないので。（市町村側がバッジを発行する場合もあると聞いた）
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/208#issuecomment-1988341204_
> feat: 大学トップ→発行元

- frontend/templates/Discover.tsx
> それでも見た目で気になるのであれば、配置をそのまま、
> タイトルに下線を引くべきでしょう。
> 
> <img width="617" alt="image" src="https://github.com/npocccties/oku-private/assets/281424/6d2da551-a7f3-44e1-aba9-630b620a0a4d">
> 
> このタイミングで検討課題が増えれば開発工数に収まらなくなることも想定して議論させていただけたら助かります。
_Originally posted by @Hidetaro7 in https://github.com/npocccties/oku-private/issues/208#issuecomment-1987437778_
> feat: 学びを探す見出しとページコンテンツの関連を境界線で表現する

- frontend/components/SearchForm.tsx
隣接してボタンが配置されている場合、検索欄のボタンに誤認されうる
検索欄に検索ボタンを配置することで対処
> キーワード検索の検索ボタンは残した方が良いかもしれません。
> 横にログインボタンがあるため，キーワード入力後，間違えてログインボタンを押してしまいそうになる。
> 
> ![image](https://github.com/npocccties/oku-private/assets/8957521/0f97ec6d-f842-4535-93cc-d65dcc12ee3c)
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/208#issuecomment-1988314028_
変更後
> feat: 検索アイコンは検索ボタンにする

- frontend/pages/index.tsx
プロダクトのメッセージをメタタグに含んでおくことが
ブランディングの観点で望ましい
> feat: トップページのtitleはキャッチコピーを含める

- frontend/examples/concept.md
- frontend/lib/contents.ts
- frontend/lib/title.ts
- frontend/templates/Top.tsx
> @knokmki612 
> 
> https://github.com/npocccties/oku-private/issues/208#issuecomment-1990971066
> 
> > OZONE-eduの文字表記について未定義である。検討結果としてはOZONE-eduにする。
> 
> 上記の件について，大教大側の回答として，文字の表記は「OZONE-EDU」で確定と連絡がありました。
> 
> お手数ですが，head情報（<title>学びを探す - OZONE-edu</title>など）やメニュー（OZONE-edu について）など，文字表記部分の修正をお願いします。
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/211#issuecomment-1996230321_
> feat: OZONE-edu → OZONE-EDU

- frontend/components/LearningContents.tsx
- frontend/components/PostLink.tsx
- frontend/templates/Issuer.tsx
- frontend/templates/Posts.tsx
@knokmki612 
おしらせについて，日時エリアがタイトルに押されないようにして欲しい
（[Figma](https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OZONE-EDU?type=design&node-id=1605-11161&mode=design&t=5oSU2VxCiaX2bwKA-0)ではタイトル長くても押されていないので同じように。）
https://o3edu.osaka-kyoiku.ac.jp/issuers/1
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/211#issuecomment-2006967715_
@knokmki612
提供するコンテンツの左のラインが水色になっていました。お知らせ側のラインと揃っていないから間違えているのかも。（Figmaも灰色ですし）
https://o3edu.osaka-kyoiku.ac.jp/issuers/1
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/211#issuecomment-2007187729_
> fix: おしらせ名文字列長によって日付が折り返されうる, etc.

- frontend/.env.development
https://github.com/npocccties/chiloportal/commit/76dfad59980f80e4e015fb4f9e1064ef8e5b32a4#diff-8418659e03d1d6494d6c53bd2f591905fdc4369cf108de7b249bb796fb88aa1bR3
@knokmki612 
.env.development ファイル内の環境変数名のミス
3行目は，NEXT_PUBLIC_API_BASE_URLではなく，NEXT_PUBLIC_BASE_URL かと思います。
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/211#issuecomment-2005869310_
> fix: 意図しない環境変数の重複

- frontend/pages/issuers/[issuerId]/index.tsx
@knokmki612 
組織別の能力バッジのところにあるカテゴリの数が組織別でなく全体で出ているのは想定通りでしょうか？
https://o3edu.osaka-kyoiku.ac.jp/issuers/2
_Originally posted by @ties-makimura in https://github.com/npocccties/oku-private/issues/211#issuecomment-2011314150_
> fix: カテゴリー別バッジの件数が組織別ではなく全体で抽出している

- frontend/pages/_document.tsx
> fix: ogp `og:` 名前空間宣言が未定義

- frontend/components/Chat.tsx
ref #868
チャットボットでの検索APIリクエスト時と同一の
正規化や改行の除去をおこなった文字列を使用することで対処します
> fix: チャットから検索ページに遷移した際に改行が検索語句に含まれうる

- frontend/README.md
- frontend/lib/env.ts
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/yarn.lock
ref https://github.com/npocccties/chiloportal/issues/858
- 動作検証のための Google タグ ID をハードコーディングしています
- Google タグ ID は環境変数 `NEXT_PUBLIC_GOOGLE_TAG_ID` により変更可能です
> feat: Google Analytics 設置

- frontend/lib/badge-status-list.test.ts
- frontend/lib/badge-status-list.ts
- frontend/mocks/handlers.ts
- frontend/package.json
- frontend/pages/api/verify-cookie.ts
- frontend/pages/dashboard.tsx
- frontend/templates/Dashboard.tsx
- frontend/yarn.lock
resolve https://github.com/npocccties/oku-private/issues/242 , resolve https://github.com/npocccties/chiloportal/issues/911
- 受講中かつ未インポートのとき受講中のコースに分類
- インポート済みのとき獲得済みのバッジに分類
- 獲得済みのバッジはインポート日時降順に並べ替え
- 受講中のバッジは次に並べ替え
- 最終アクセス日時降順に並べ替え
- 発行済みかつ未インポートを優先
> 受講中のコース & 獲得済みのバッジの並びと分類

- Dockerfile.frontend
- frontend/lib/markdown.ts
- frontend/package.json
- frontend/yarn.lock
fix: #928
SSR 時にマークダウン記事を取得、表示に使用する目的
確認方法
1. cd frontend
2. cp examples/post.md contents/
3. docker build -t frontend -f ../Dockerfile.frontend ..
4. docker run --env JWT_VERIFICATION_KEY=xxx --rm -p 3000:3000 frontend
スクリーンショット
> fix(markdown): .next/server/* から contents ディレクトリを探索する

- frontend/components/EarnedBadge.tsx
- badge_json プロパティのパース結果の値はすべて optional にします
- image プロパティの値は string | object 形式をサポートします
> fix(dashboard): 獲得したバッジの画像 URL 参照に失敗

- frontend/components/CurrentCourse.tsx
- frontend/components/EarnedBadge.tsx
非フォーカス（blur）になるまで表示する場合、表示領域を専有するため
閲覧者が非フォーカスに出来ずに裏に隠れた情報に閲覧できない可能性が
あります。
3秒経過したら表示を解消する実装にすることで対処します。
> feat: 受講中のコースまたは獲得したバッジの選択不可を時限的に表示する

- frontend/templates/Dashboard.tsx
grid layout として実装した際にそれぞれ等しい grid area とみなしていた
ことが原因
div でラップすることで一つの gird area とみなすことで対処
> fix: タブと article 要素間に意図しない余白が生じる

- frontend/pages/dashboard.tsx
- frontend/templates/Dashboard.tsx
未ログイン時ログインページへのリダイレクトはせず、文面にログインリンクを含む未ログイン者向けの表示がされるように変更します。
> feat(dashboard): 未ログイン表示

- frontend/templates/Top.tsx
> feat: トップページからお知らせリンクを削除
