npocccties/chiloportal

.github/workflows/frontend.yaml

resolve #5
- コード整形
- 静的コード検査
- ビルドテスト
をおこなう CI の導入
ユニットテストについては現状テストするものがないので必要になったら別課題で導入

chore: CI の設定

---

frontend/README.md

docs(frontend): 開発方法、デプロイ方法、スクリプト

---

backend/doc/openapi.json
frontend/mocks/handlers.ts

fix: categoly → category

---

frontend/.env.development
frontend/README.md

chore: Moodle ダッシュボードの URL の環境変数の設定

---

backend/doc/openapi.yaml
backend/openapi.yaml

UIに合わせた仕様の変更、および、用語の最終案に対応しました。

OpenAPI（用語最終案対応）

---

backend/Dockerfile
backend/README.md

postgresのCLIをインストール

---

backend/chiloportal/responses.py
backend/chiloportal/tests/views/base_api_view_tests.py
backend/doc/openapi.yaml
frontend/mocks/faker.ts

feat: degital_badge_class_id → digital_badge_class_id

---

frontend/components/Header.tsx
frontend/components/Layout.tsx
frontend/components/Popover.tsx
frontend/pages/_app.tsx

feat: 共通ヘッダーの実装

---

frontend/components/Header.tsx

画面遷移を伴う箇所は a 要素を用いたほうがセマンティクス的によりよいため

feat: next/link で a 要素を使う

---

frontend/components/Header.tsx
frontend/pages/portal_categories/[portalCategoryId].tsx
frontend/pages/search.tsx

pathpida に検知してもらうのに必要
https://github.com/aspida/pathpida#define-query---nextjs

feat: 画面のクエリパラメータの型

---

frontend/.editorconfig

デフォルト設定の Prettier と競合しているので競合しない設定値にする目的

chore: editorconfig の調整

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/config.yaml
frontend/lib/post.ts
frontend/package.json
frontend/pages/index.tsx
frontend/pages/posts/[slug].tsx
frontend/pages/posts/index.tsx
frontend/posts/test.md
frontend/tailwind.config.js
frontend/templates/Post.tsx
frontend/templates/Posts.tsx
frontend/templates/Top.tsx
frontend/yarn.lock

resolve #85 , resolve #86 , resolve #87 , resolve #88 , resolve #84

feat: おしらせ/おしらせ一覧画面の実装 

---

frontend/components/PortalCategoryCard.tsx
frontend/components/WisdomBadgesCard.tsx
frontend/config.yaml
frontend/lib/use-badges.ts
frontend/package.json
frontend/pages/index.tsx
frontend/tailwind.config.js
frontend/templates/Top.tsx
frontend/yarn.lock

resolve #46 , resolve #53 , resolve #54

feat: 能力バッジとポータルカテゴリのカードコンポーネントの実装

---

frontend/.env.test

chore: テスト用環境変数の設定

---

frontend/components/Breadcrumbs.tsx
frontend/templates/Post.tsx
frontend/templates/Posts.tsx

feat: ぱんくずリストの実装

---

frontend/.env.test
frontend/Dockerfile
frontend/README.md

chore: NEXT_PUBLIC_API_BASE_PATH の https への差し替え

---

frontend/components/Container.tsx
frontend/components/Pagination.tsx
frontend/components/WisdomBadgesItem.tsx
frontend/lib/use-pagination.ts
frontend/mocks/faker.ts
frontend/mocks/handlers.ts
frontend/pages/portal_categories/[portalCategoryId].tsx
frontend/templates/PortalCategory.tsx
frontend/templates/Post.tsx
frontend/templates/Posts.tsx
frontend/templates/Top.tsx

feat: ポータルカテゴリトップ画面の実装

---

frontend/components/SearchForm.tsx
frontend/pages/search.tsx
frontend/templates/Search.tsx
frontend/templates/Top.tsx

feat: 検索結果画面の実装

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/contents/about_site.md
frontend/contents/about_us.md
frontend/contents/concept.md
frontend/contents/contact.md
frontend/contents/disclaimer.md
frontend/contents/privacy_policy.md
frontend/lib/content.ts
frontend/pages/[slug].tsx
frontend/templates/Content.tsx

feat: 静的ページの実装

---

frontend/.eslintrc.yaml
frontend/lib/use-portal-categories.ts
frontend/package.json
frontend/pages/_app.tsx
frontend/templates/WisdomBadges.tsx
frontend/yarn.lock

chore: filename-match-exported 規約の導入

---

frontend/components/KnowledgeBadgesItem.tsx
frontend/components/WisdomBadgesCard.tsx
frontend/components/WisdomBadgesDialog.tsx
frontend/components/WisdomBadgesItem.tsx
frontend/lib/use-badges-frameworks.ts
frontend/lib/use-dialog.ts
frontend/pages/wisdom_badges/[wisdomBadgesId].tsx
frontend/tailwind.config.js
frontend/templates/PortalCategory.tsx
frontend/templates/Search.tsx
frontend/templates/WisdomBadges.tsx

feat: 能力バッジ画面の実装

---

frontend/Dockerfile
frontend/mocks/faker.ts

chore: OpenAPI ドキュメントの v0.9.5 への追従

---

frontend/components/StagesTable.tsx
frontend/mocks/faker.ts
frontend/templates/Frameworks.tsx

resolve #50 , resolve #64 , resolve #64

feat: 育成指標から成長段階を選ぶ画面の実装

---

frontend/components/Container.tsx
frontend/components/FieldsIndex.tsx
frontend/components/StagesDialog.tsx
frontend/components/StagesTable.tsx
frontend/lib/field.ts
frontend/mocks/handlers.ts
frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
frontend/templates/Stage.tsx

feat: 成長段階別バッジ一覧画面の実装

---

frontend/components/Header.tsx
frontend/components/Popover.tsx

画面遷移を伴う場合 Popover が閉じられたほうが操作性の観点でよりよいため

feat: Popover クリック時 Popover が閉じられるように

---

frontend/pages/portal_categories/[portalCategoryId].tsx
frontend/pages/search.tsx

fix: page_number クエリパラメーターが適切に渡せていない

---

frontend/components/Chat.tsx

fix: チャットがモバイル表示時見切れる

---

backend/chiloportal/tests/views/localhost/test_consumer_detail.py
backend/chiloportal/tests/views/localhost/test_framework.py
backend/chiloportal/views/consumer_detail.py
backend/chiloportal/views/framework_detail.py
backend/doc/openapi.yaml

This reverts commit 0be95466bde4355f2a1d5e9f38f5f826101e8044.

Revert "fix: 単独データを返すAPIは404のままとしたほうがいいかもしれないので、元に戻す"

---

frontend/pages/search.tsx

feat: キーワードが空文字列の場合 API コールしない

---

frontend/Dockerfile
frontend/components/FieldsIndex.tsx
frontend/mocks/handlers.ts
frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
frontend/templates/Stage.tsx

feat: /stage/field/list のレスポンス変更への追従

---

frontend/README.md
frontend/components/WisdomBadgesCard.tsx
frontend/components/WisdomBadgesItem.tsx
frontend/lib/env.ts

feat: 能力バッジ発行者の画像

---

frontend/templates/WisdomBadges.tsx

feat: コースへの動線

---

.github/workflows/cd.yml

chore: フロントエンド変更時も CD するように

---

frontend/components/KnowledgeBadgesItem.tsx
frontend/mocks/faker.ts

参考 https://dev-portal.oku.cccties.org/wisdom_badges/101

fix: criteria.name に番号が含まれるのでスタイルでは表現不要

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/components/WisdomBadgesDialog.tsx
frontend/lib/client.ts
frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
frontend/pages/consumers/[consumerId]/index.tsx
frontend/pages/portal_categories/[portalCategoryId].tsx
frontend/pages/search.tsx
frontend/pages/wisdom_badges/[wisdomBadgesId].tsx
frontend/templates/Top.tsx

feat: データ取得の例外処理

---

backend/deploy.sh

resolve #376
存在しないコンテナーを停止しようとしていることが原因
存在するかに関わらず実行し処理を継続してもらうことで対処

fix: No such container: frontend

---

frontend/lib/client.ts

fix: 200 HTTP ステータス以外かつ { detail: string } のレスポンスの場合が考慮していない

---

frontend/Dockerfile

fix: あやまった Docker ベースイメージの指定

---

frontend/lib/markdown.ts
frontend/lib/rehype-image-size.ts
frontend/package.json
frontend/pages/[slug].tsx
frontend/pages/index.tsx
frontend/pages/posts/[slug].tsx
frontend/pages/posts/index.tsx
frontend/schemas/frontmatter.ts
frontend/templates/Content.tsx
frontend/templates/Post.tsx
frontend/tsconfig.json
frontend/vfile-env.d.ts
frontend/yarn.lock

feat: 記事画像の next/image での表示

---

.github/workflows/frontend-docker.yaml

chore: Docker イメージビルドの CI でのテスト

---

frontend/.gitignore
frontend/config.yaml
frontend/lib/config.ts
frontend/lib/markdown.ts
frontend/lib/use-badges.ts
frontend/posts/test.md

https://github.com/npocccties/chiloportal/issues/428#issuecomment-1298217892 への対応

feat: config.yaml と posts/*.md について Git 管理対象外にする

---

frontend/components/PortalCategoryCard.tsx
frontend/templates/Top.tsx

feat(PortalCategoryCard): 説明文を全文表示するように

---

frontend/lib/markdown.ts

事前に .keep については内容を読み込まないよう除外することで対処

fix: .keep が混入しうる

---

frontend/.gitignore
frontend/README.md
frontend/config.yaml
frontend/lib/config.ts
frontend/lib/markdown.ts
frontend/posts/test.md

feat: 静的コンテンツの上書き対応

---

frontend/.dockerignore
frontend/Dockerfile

- 共通のレイヤーを参照するようなマルチステージビルドの追加
- 明示的な COPY 対象の指定
このリファクタリングでビルド毎にレイヤーキャッシュが更新されていた現象も改善する可能性があります

refactor: Dockerfile

---

frontend/README.md
frontend/config.yaml
frontend/schemas/config.ts

feat: learningContents の拡張

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/templates/Frameworks.tsx
frontend/templates/Stage.tsx
frontend/templates/Top.tsx
frontend/templates/WisdomBadges.tsx

feat: 育成指標 → 教員育成指標

---

frontend/lib/rehype-image-size.ts
frontend/templates/Content.tsx
frontend/templates/Post.tsx

feat: マークダウンファイルの外部 URL の画像表示

---

frontend/components/Footer.tsx
frontend/components/Header.tsx

feat: グローバルメニューフッターの見た目の更新

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/contents/concept.md

feat: コンセプト→OKUTEPについて

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/contents/about_operator.md
frontend/contents/about_site.md
frontend/contents/copyright.md

feat: グローバルメニューの更新

---

frontend/components/Fallback.tsx
frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/components/WisdomBadgesDialog.tsx
frontend/templates/Top.tsx

feat: 認定している教育委員会が存在しない場合の見た目

---

frontend/templates/Top.tsx

feat: 教員育成指標の説明

---

frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
frontend/templates/Stage.tsx

あやまった配列の添字を指定していることが原因
field_idを添字として使用するように構造を変更することで対処

fix: 指標項目と能力バッジの表示が一致していない

---

frontend/templates/Content.tsx
frontend/templates/Post.tsx

feat: 記事を表示するページの h1 見出しの見た目を本文と揃える

---

frontend/templates/Top.tsx

feat: 少ない回数で獲得できる能力バッジ → 試しに受講してみる

---

frontend/contents/about_badges.md
frontend/templates/Top.tsx

feat: 能力バッジとは？ページの追加

---

frontend/components/PortalCategoryCard.tsx
frontend/components/WisdomBadgesCard.tsx
frontend/templates/Top.tsx

feat: ポータルトップの見た目の更新

---

frontend/components/KnowledgeBadgesItem.tsx
frontend/components/WisdomBadgesItem.tsx
frontend/package.json
frontend/tailwind.config.js
frontend/yarn.lock

feat: line-clamp を取り除く

---

frontend/templates/Top.tsx

feat: ポータルトップにおけるポータルカテゴリーの説明

---

frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/components/Menu.tsx
frontend/components/Popover.tsx
frontend/lib/contents.ts

feat: モバイル表示時のグローバルメニューヘッダーの見た目の更新

---

frontend/contents/about_site.md
frontend/contents/about_us.md
frontend/lib/contents.ts

以下への対応です
> フッターは以下の通りでお願いします．
> 「お問い合わせ」はそのまま残しておく
> 「私たちについて」→「このサイトについて」に文言なおす

feat: 私たちについて→このサイトについて

---

frontend/lib/title.ts
frontend/pages/_app.tsx

feat: 全体のページタイトル

---

frontend/components/Breadcrumbs.tsx
frontend/components/Chat.tsx
frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/components/Link.tsx
frontend/components/Menu.tsx
frontend/components/Pagination.tsx
frontend/components/PortalCategoryCard.tsx
frontend/components/StagesTable.tsx
frontend/components/WisdomBadgesCard.tsx
frontend/components/WisdomBadgesItem.tsx
frontend/templates/Posts.tsx
frontend/templates/Top.tsx

feat: ページ遷移時ページ上部へのスクロールを無効化

---

frontend/components/Chat.tsx

feat: 画面遷移時チャットを閉じるように

---

frontend/components/Chat.tsx
frontend/package.json
frontend/yarn.lock

feat: チャットの入力欄は改行時リサイズするように

---

frontend/components/Chat.tsx
frontend/components/Header.tsx

fix: ダークモードについて考慮できていない

---

frontend/pages/[slug].tsx
frontend/pages/_app.tsx
frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
frontend/pages/consumers/[consumerId]/index.tsx
frontend/pages/index.tsx
frontend/pages/portal_categories/[portalCategoryId].tsx
frontend/pages/posts/[slug].tsx
frontend/pages/posts/index.tsx
frontend/pages/search.tsx
frontend/pages/wisdom_badges/[wisdomBadgesId].tsx

feat: 個別のページタイトル

---

frontend/components/Header.tsx

fixed #630 
This reverts commit 96fd8d5e349df54490b502de3999ea1e4b9862e9.

Revert "feat: 特定の幅の際グローバルヘッダーを横スクロールするように"

---

frontend/components/Footer.tsx
frontend/components/Header.tsx

ロゴ画像を差し替えたことにより期待するクリッカブルな領域が
変わっているように思うのでそのことへの対応

feat: ロゴの余白の調整

---

frontend/templates/WisdomBadges.tsx

feat: 「認定している教育委員会を見る」へ文言変更

---

frontend/templates/Top.tsx

feat: サイトの説明の見た目の更新

---

frontend/components/Header.tsx
frontend/templates/Top.tsx
frontend/templates/WisdomBadges.tsx

feat: Moodle へのリンクは同じウィンドウで開くように

---

ARCHITECTURE.md

フロントエンドのフレームワークとコードマップのドキュメンテーションです

docs: フロントエンドのアーキテクチャ

---

.github/workflows/frontend-docker.yaml
.github/workflows/frontend.yaml
frontend/Dockerfile
frontend/README.md
frontend/package.json

chore(deps): Node.js v20

---

frontend/Dockerfile

fix: フロントエンド CI で Docker イメージのビルドに失敗する

---

.github/workflows/frontend.yaml
frontend/Dockerfile
frontend/mocks/faker.ts
frontend/mocks/handlers.ts

https://github.com/npocccties/chiloportal/pull/712 時点のOpenAPIに記載のある仕様に対応します

feat(frontend): /consumer/goal/list, /consumer/badges/list 対応

---

frontend/lib/client.ts
frontend/lib/node-client.ts
frontend/package.json
frontend/pages/consumers/[consumerId]/frameworks/[frameworkId]/stages/[stageId].tsx
frontend/pages/consumers/[consumerId]/index.tsx
frontend/pages/portal_categories/[portalCategoryId].tsx
frontend/pages/search.tsx
frontend/pages/wisdom_badges/[wisdomBadgesId].tsx
frontend/yarn.lock

resolve #713
Next.js が提供する fetch ではなく node-fetch を使用することで対処

fix: Next Server側で aspida client 使用時データ取得に失敗

---

frontend/.eslintrc.yaml
frontend/components/Fallback.tsx
frontend/package.json
frontend/templates/Content.tsx
frontend/templates/Post.tsx
frontend/templates/Top.tsx
frontend/yarn.lock

chore: typescript-eslint 導入

---

frontend/templates/Issuer.tsx

resolve #685
その他コンテンツの表示に対応する見出しがおすすめバッジで不一致な点を正します。

fix: あやまったラベリング

---

frontend/tailwind.config.js

https://www.figma.com/file/dCE06JShf29eqnvZ4vcE8U/OZONE-edu?type=design&node-id=731-6618&mode=design&t=QSV6Ns3J86FynYGB-4 に追従します。
resolve #738 
変更前
変更後

feat: カラースキームの更新

---

frontend/examples/issuer-1-post.md
frontend/examples/issuer-1.yaml
frontend/lib/get-static-issuer-ids.ts
frontend/pages/issuers/[issuerId]/index.tsx
frontend/pages/issuers/[issuerId]/posts/[slug].tsx
frontend/templates/Issuer.tsx
frontend/templates/Post.tsx

feat: 大学別おしらせページ

---

backend/chiloportal/tests/views/localhost/base_api_view_tests.py
backend/chiloportal/tests/views/localhost/test_badges_list.py
backend/chiloportal/urls.py
backend/chiloportal/views/badges_list.py
backend/doc/openapi.yaml

https://github.com/npocccties/chiloportal/issues/754
https://github.com/npocccties/chiloportal/issues/765#issuecomment-1855334636
上記記載の内容より、APIを作成

発行機関が何件の能力バッジを発行したか分かるようになる

---

frontend/pages/discover.tsx
frontend/templates/Discover.tsx
frontend/templates/Top.tsx

feat: トップから能力バッジを探す画面への動線

---

backend/chiloportal/tests/views/localhost/base_api_view_tests.py
backend/chiloportal/tests/views/localhost/test_badges.py
backend/chiloportal/views/badges_detail.py

下記Issueの対応分です。
https://github.com/npocccties/chiloportal/issues/669

feat: クライテリアの表示順を sort_key 順にする

---

frontend/templates/Discover.tsx

feat: 成長段階はタブとして実装する

---

deploy.sh

resolve #805
移動したシェルスクリプトを実行するように見直すことで対処

fix: 存在しないシェルスクリプトを実行しようとしている

---

frontend/components/Container.tsx
frontend/components/FieldsIndex.tsx
frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/templates/Content.tsx
frontend/templates/Discover.tsx
frontend/templates/Issuer.tsx
frontend/templates/Post.tsx
frontend/templates/Posts.tsx
frontend/templates/Search.tsx
frontend/templates/Top.tsx
frontend/templates/WisdomBadges.tsx

resolve #813
以下を基準として余白のスタイルを整理します
- 上下左右: 24px
- 最下部: 40px
- gap: 24px

feat: 余白の取扱いの更新

---

frontend/components/WisdomBadgesItem.tsx

feat(WisdomBadgesItem): モバイル表示の見た目

---

frontend/templates/Content.tsx
frontend/templates/Post.tsx

feat: お知らせとその他静的ページの見た目の整理

---

frontend/templates/Post.tsx
frontend/templates/Posts.tsx

feat: 大学連携お知らせ一覧画面の見た目の整理

---

frontend/next.config.js

See https://github.com/gregberge/svgr/discussions/826

fix: リサイズ時ソースのサイズが優先され見切れる

---

frontend/pages/discover.tsx
frontend/templates/Discover.tsx
frontend/templates/Top.tsx
frontend/templates/WisdomBadges.tsx

feat: バッジを探す→学びを探す

---

frontend/templates/Posts.tsx

feat: お知らせ一覧のモバイルでの見出しを小さくする

---

frontend/pages/[slug].tsx
frontend/pages/index.tsx
frontend/pages/issuers/[issuerId]/posts/[slug].tsx
frontend/pages/posts/[slug].tsx

MDX 形式としてパースされ使用不可なプロパティ（class）を使用しているため
md 形式でパースされるように指定して対処

fix: 無効なプロパティを使用している

---

frontend/components/DiscoverNav.tsx
frontend/templates/Discover.tsx

feat: 教育委員会→教員育成指標

---

frontend/components/Container.tsx
frontend/components/Footer.tsx
frontend/components/Header.tsx
frontend/templates/Top.tsx

feat: グローバルフッターの整理

---

frontend/README.md
frontend/examples/custom-top.md

fix: MDX として無効なプロパティを使用している

---

frontend/components/KnowledgeBadgesItem.tsx
frontend/templates/Issuer.tsx
frontend/templates/WisdomBadges.tsx

feat: 能力バッジ画面の見た目の整理

---

frontend/templates/Issuer.tsx
frontend/templates/WisdomBadges.tsx

全体を含んでアスペクト比を維持して表示されるように指定し対処

fix: 大学ロゴが見切れる

---

frontend/templates/Search.tsx

feat: キーワード検索のページネーションのレイアウト調整

---

.github/workflows/frontend.yaml
frontend/README.md
frontend/components/Pagination.tsx
frontend/lib/env.ts
frontend/lib/use-pagination.test.ts
frontend/lib/use-pagination.ts
frontend/package.json
frontend/yarn.lock

ページあたり件数を開始地点と終了地点で算出し可変であることが原因
ページあたり件数は環境変数 NEXT_PUBLIC_API_PER_PAGE に指定し、
バックエンドの環境変数 PER_PAGE と揃えてください @ties-makimura

fix!: 特定の条件でページネーションが存在しないページ数になる

---

frontend/styles/globals.css

fix: #848
見た目の一貫性を重視してこれらは使用しないようにします

feat: 最近の検索クエリや検索キャンセルの見た目は表示しない

---

frontend/templates/Discover.tsx
frontend/templates/Issuer.tsx

fix: 左右のコンテンツ量に応じて幅が可変、etc.

---

frontend/components/Chat.tsx

resolve #868 
キーワード検索APIが受け付けるデリミタ（半角全角スペース）に変換
することで対処します
あわせてユニコード正規化（NFC）を実施します

fix: 意図しない改行が検索文字列に含まれる

---

frontend/README.md
frontend/lib/env.ts
frontend/pages/_app.tsx

feat: Google Analytics 追跡処理をインスタンス単位で無効可能にする

---

frontend/package.json
frontend/yarn.lock

chore(deps): yarn v4.9.1

---

frontend/components/Popover.tsx
frontend/templates/Discover.tsx

- MutableRefObject: React v19 にて非推奨
- Popover.\* Disclosure.\*: v2 にて非推奨 https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.0.0

refactor: 非推奨な型、コンポーネントを使用しない

---

frontend/.env.development
frontend/.gitignore
frontend/.prettierignore
frontend/README.md
frontend/components/Header.tsx
frontend/components/Menu.tsx
frontend/components/SearchForm.tsx
frontend/components/UserPopover.tsx
frontend/eslint.config.js
frontend/lib/env.ts
frontend/lib/use-user-attributes.ts
frontend/package.json
frontend/pages/api/verify-cookie.ts
frontend/yarn.lock

resolve https://github.com/npocccties/chiloportal/issues/899 , resolve https://github.com/npocccties/chiloportal/issues/879
次の変更が含まれます
環境変数を追加します
- ログイン URL
- ログアウト URL
- JWT 署名検証鍵（PEM 形式）
- バッジウォレット ベース URL
- バッジウォレット API ベース URL
サーバー側でクッキー値のJWTを検証します
セッションクッキーからログイン中のユーザーの表示名をUIに使用します

Shibboleth sp support

---

frontend/pages/dashboard.tsx

feat: 不要な console.log の除去

---

frontend/README.md
frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx
frontend/lib/env.ts
frontend/pages/dashboard.tsx
frontend/templates/Dashboard.tsx

resolve https://github.com/npocccties/chiloportal/issues/901 , resolve https://github.com/npocccties/chiloportal/issues/907
スクリーンショット

feat: ダッシュボードの各種リンクとレスポンシブ表示

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx

resolve https://github.com/npocccties/chiloportal/issues/906
スクリーンショット

feat(dashboard): 「有効期限切れ」「提出済み」のステータス表示

---

frontend/templates/Dashboard.tsx

feat: バッジウォレット API エラーコードに応じたメッセージ通知

---

frontend/lib/use-user-attributes.ts
frontend/pages/api/verify-cookie.ts
frontend/pages/dashboard.tsx
frontend/templates/Dashboard.tsx

feat(dashboard): 受講中のコースと獲得したバッジがない時の表示

---

frontend/templates/Dashboard.tsx

feat(dashboard): エラーコード表示は INFO レベル & 共通のメッセージにする

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx

獲得可能な場合のステータス表示 & 獲得・提出不可の理由の通知

---

frontend/public/badge-placeholder.svg

ref #932
https://github.com/npocccties/chiloportal/issues/932#issuecomment-2865409061 の画像に差し替えます

feat: バッジのプレースホルダー画像の更新

---

frontend/components/EarnedBadge.tsx

fix: badge_json は "null" またはエラーオブジェクト（のJSON文字列）が渡されうる

---

frontend/components/EarnedBadge.tsx

ref #932
- badge_json のバリデーション関数を定義します
- バリデーション関数の結果により提出可否を判定します
- バリデーション関数や badge_json のパース、正規化処理を整理します

fix: badge_json プロパティが undefined ではないとき提出可能

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx
frontend/package.json
frontend/yarn.lock

feat: 受講中のコース、獲得したバッジは説明文を表示しない

---

frontend/templates/Dashboard.tsx

feat(dashboard): 獲得、提出のボタンのカーソルをポインターにする

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx

1. LMS 名
2. コース or バッジ名
3. ステータス
を縦並びに表示するように変更します

feat: 受講中のコースと獲得したバッジの表示項目の並び変更

---

frontend/templates/Dashboard.tsx

Reverts npocccties/chiloportal#948

Revert "fix: タブと article 要素間に意図しない余白が生じる"

---

frontend/templates/Dashboard.tsx

Reverts npocccties/chiloportal#949

Revert "Revert "fix: タブと article 要素間に意図しない余白が生じる""

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx

領域内コンテンツ量で可変幅になっているのを明示的に幅を指定するように変更します

feat: 最大幅の設定

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx

clearTimeout() により過去の setTimeout() 処理をキャンセルし、
最後に設定されたタイムアウト処理のみ実行します

feat: 未発火タイムアウト処理のキャンセル

---

frontend/components/CurrentCourse.tsx
frontend/components/EarnedBadge.tsx
frontend/package.json
frontend/yarn.lock

遅延処理を debounce パターンとそれを抽象化するライブラリに委ねます

feat: タイムアウト処理を use-debounce に置き換え

---

frontend/templates/Dashboard.tsx

feat: バッジの提出から戻る先は獲得したバッジのタブにする

---

frontend/templates/Dashboard.tsx

Reverts npocccties/chiloportal#957

Revert "feat(dashboard): 未ログイン時は「ゲスト」をユーザー名として表示する"

---

frontend/components/Header.tsx
frontend/components/Menu.tsx
frontend/components/UserPopover.tsx
frontend/pages/dashboard.tsx
frontend/templates/Dashboard.tsx

- ダッシュボードは未ログイン時ログイン画面にリダイレクトします
- 未ログイン時ヘッダーにログインリンクを表示します

feat: ゲスト表記の廃止

---

frontend/components/Header.tsx

fix: 特定のビューポート幅をヘッダーがはみ出る

---

frontend/pages/dashboard.tsx

https://github.com/npocccties/chiloportal/pull/960 改め，リダイレクトだけはしておく

feat: 未ログイン時ログインページに遷移
